# *********************Settings Test Constants**********************

MAIL_PASSWORD = 'abc'
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_TLS = True
MAIL_USE_SSL = True
MAIL_USERNAME = 'Paul'
FBOOK_APP_TOKENS = ('Paul01', 'abCD123ef')
TWIT_APP_TOKENS = ('Paul01', 'abCDef123hi')
GIT_APP_TOKENS = ('Paul01', 'abCD-ef123hi')
GOOGLE_APP_TOKENS = ('Paul01', 'abCD-ef123hi/456')
SERVICE_TOKENS = ('Paul01', 'abCD-ef123hi/456')
ROS_DISTRIBUTION = 'indigo'
SQLALCHEMY_DATABASE_URI = 'postgresql://docker@127.0.0.1:5432/docker'
POSTGRES_PORT_5432_TCP_ADDR = '127.0.0.1'
POSTGRES_PORT_5432_TCP_PORT = '5432'
NULL_TOKENS = (None,None)

DOCKBRIDGE_PORT_5001_TCP_ADDR = '170.17.0.60'
DOCKBRIDGE_PORT_5001_TCP_PORT = '5001'

URL = 'http://170.17.0.60:5001'

OAUTH_TOKENS = ('Paul01', 'abCD-ef123hi/456')

GIT_REPO = 'git https://github.com/PR2/pr2_common'
SVN_REPO = 'svn https://svn.com/PR2/pr2_common'
OPENEASE_MESH_REPOS = '{},{}'.format(GIT_REPO,SVN_REPO)
MESH_REPOSITORIES = [('git', 'https://github.com/PR2/pr2_common'), ('svn', 'https://svn.com/PR2/pr2_common')]
MESH_REPO_DEFAULT = [('git', 'https://github.com/PR2/pr2_common')]

OPENEASE_MAIL_PASSWORD = 'OPENEASE_MAIL_PASSWORD'
OPENEASE_MAIL_SERVER = 'OPENEASE_MAIL_SERVER'
OPENEASE_MAIL_PORT = 'OPENEASE_MAIL_PORT'
OPENEASE_MAIL_TLS = 'OPENEASE_MAIL_USE_TLS'
OPENEASE_MAIL_SSL = 'OPENEASE_MAIL_USE_SSL'
OPENEASE_MAIL_USERNAME = 'OPENEASE_MAIL_USERNAME'
POSTGRES_PORT_TCP_ADDR = 'POSTGRES_PORT_5432_TCP_ADDR'
POSTGRES_PORT_TCP_PORT = 'POSTGRES_PORT_5432_TCP_PORT'
OPENEASE_ROS_DISTRIBUTION = 'OPENEASE_ROS_DISTRIBUTION'
DOCKERBRIDGE_PORT_TCP_ADDR = 'DOCKERBRIDGE_PORT_5001_TCP_ADDR'
DOCKERBRIDGE_PORT_TCP_PORT = 'DOCKERBRIDGE_PORT_5001_TCP_PORT'
OPENEASE_MESHES = 'OPENEASE_MESHES'

FBOOK_APP_ID = 'FACEBOOK_APP_ID'
FBOOK_APP_SECRET = 'FACEBOOK_APP_SECRET'
TWIT_APP_ID = 'TWITTER_APP_ID'
TWIT_APP_SECRET = 'TWITTER_APP_SECRET'
GIT_APP_ID = 'GITHUB_APP_ID'
GIT_APP_SECRET = 'GITHUB_APP_SECRET'
GOOGLE_APP_ID = 'GOOGLE_APP_ID'
GOOGLE_APP_SECRET = 'GOOGLE_APP_SECRET'


